language: python
sudo: false
cache: pip
dist: trusty

matrix:
  fast_finish: true

install:
  - "pip install --upgrade pytest-cov pytest-timeout pytest pip pipenv --upgrade-strategy=eager"
  - "pipenv install --dev"
  - "pipenv run pip install --upgrade -e .[tests] pytest pytest-timeout pytest-cov --upgrade-strategy=eager"
script:
    - "pipenv run pytest -ra tests/"

jobs:
  include:
    - stage: test
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "2.7"
    - python: "3.5"
    - python: "3.4"
    - stage: packaging
      python: "3.6"
      install:
        - "pip install --upgrade setuptools twine readme_renderer[md]"
      script:
        - "python setup.py sdist"
        - "twine check dist/*"
    - stage: coverage
      python: "3.6"
      install:
        - "pip install --upgrade pip pipenv pytest-cov pytest-timeout pytest"
        - "pipenv install --dev"
      script:
        - "pipenv run pytest --timeout 300 --cov=pythonfinder --cov-report=term-missing --cov-report=xml --cov-report=html tests"
